--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_MESSAGE
--------------------------------------------------------

  CREATE TABLE "BANG"."TBL_MESSAGE" 
   (	"MID" NUMBER(*,0), 
	"TARGETID" VARCHAR2(50 BYTE), 
	"SENDER" VARCHAR2(50 BYTE), 
	"MESSAGE" VARCHAR2(500 BYTE), 
	"OPENDATE" DATE, 
	"SENDDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011648
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANG"."SYS_C0011648" ON "BANG"."TBL_MESSAGE" ("MID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_MESSAGE
--------------------------------------------------------

  ALTER TABLE "BANG"."TBL_MESSAGE" MODIFY ("MID" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_MESSAGE" MODIFY ("TARGETID" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_MESSAGE" MODIFY ("SENDER" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_MESSAGE" MODIFY ("MESSAGE" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_MESSAGE" ADD PRIMARY KEY ("MID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
