--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_USER
--------------------------------------------------------

  CREATE TABLE "BANG"."TBL_USER" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"UPW" VARCHAR2(50 BYTE), 
	"UNAME" VARCHAR2(100 BYTE), 
	"UPOINT" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011649
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANG"."SYS_C0011649" ON "BANG"."TBL_USER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_USER
--------------------------------------------------------

  ALTER TABLE "BANG"."TBL_USER" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_USER" MODIFY ("UPW" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_USER" MODIFY ("UNAME" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_USER" MODIFY ("UPOINT" NOT NULL ENABLE);
 
  ALTER TABLE "BANG"."TBL_USER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
